name: gophercon

volumes:
  root-go:
  postgres-data:


networks:
  gopher:
    name: gopher
    driver: bridge

services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    networks:
      - gopher
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    networks:
      - gopher
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --web.enable-otlp-receiver
      - --enable-feature=exemplar-storage

  loki:
    image: grafana/loki
    container_name: loki
    hostname: loki
    networks:
      - gopher
    ports:
      - 3100:3100

  tempo:
    image: grafana/tempo
    container_name: tempo
    hostname: tempo
    networks:
      - gopher
    ports:
      - 4319:4319
      - 3200:3200
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    command:
      - -config.file=/etc/tempo.yaml

  otel:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel
    hostname: otel
    networks:
      - gopher
    ports:
      - 4317:4317
      - 4318:4318
      - 8888:8888
      - 8889:8889
    volumes:
      - ./otel.yaml:/etc/otel.yaml
    command:
      - --config=/etc/otel.yaml
    depends_on:
      - tempo
      - loki

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    networks:
      - gopher
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards

    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_FEATURE_TOGGLES_ENABLE: traceqlEditor
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    depends_on:
      - otel
      - prometheus
      - loki
      - tempo